
        <footer>
            <p class="footer-item">&copy; Končák Matias</p>
            <a href="https://freedns.afraid.org/">Free DNS</a>
            <a class="footer-item footer-link" target="_blank" href="https://icons8.com">Icons by Icons8</a>
            <a class="footer-item footer-link" target="_blank" href="https://www.pexels.com/photo/golden-sunset-over-calm-ocean-waters-32266925/">Photo by Sinful</a>
        </footer>
    </div>
</body>
</html>