<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/assets/css/general.css">
    <link rel="stylesheet" href="/assets/css/nav.css">
    <link rel="stylesheet" href="/assets/css/footer.css">
    <link rel="stylesheet" href="/assets/css/toast.css">
    <link rel="stylesheet" href="/assets/css/index.css">
    <link rel="stylesheet" href="/assets/css/logreg.css">
    <link rel="stylesheet" href="/assets/css/explore.css">
    <link rel="stylesheet" href="/assets/css/account.css">
    <link rel="stylesheet" href="/assets/css/moderation.css">
    <link rel="stylesheet" href="/assets/css/overlay.css">
    <link rel="stylesheet" href="/assets/css/song.css">
    <script src="/assets/js/iframe.js" defer></script>
    <script src="/assets/js/moderation.js" defer></script>
    <script src="/assets/js/notification.js" defer></script>
    <script src="/assets/js/password.js" defer></script>
    <script src="/assets/js/overlay.js" defer></script>
    <script src="/assets/js/redirects.js" defer></script>
    <script src="/assets/js/listeners.js" defer></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Nunito:ital,wght@0,200..1000;1,200..1000&display=swap" rel="stylesheet">
    <title><?= $title ?? WEB_NAME ?></title>
</head>
<body>
    <nav class="nav-js">
        <?php
        require_once __DIR__ . "/nav.phtml";
        
        ?>

    </nav>
    <div class="container">
        <div id="toast-container"></div>