<?php if(!isset($_GET["backButton"])) {?>
    <!--<img src="/img/back-button.png" alt="Home button" onclick="redirect_home()">-->
    <form class="search-container" action="search">
        <input class="search-bar" type="text" placeholder="Enter artist or song title" id="searchTerm" name="searchTerm">
        <div class="search-button-container">
            <input class="search-button static img-button" type="submit" value="">
            <!--<input class="search-button active img-button" type="submit" value="">-->
        </div>
    </form>

<div class="nav-bar">
    <a class="nav-button" onclick="redirect_home()">Home</a>
    <a class="nav-button" onclick="redirect_explore()">Explore</a>
    <?php if (isset($_SESSION["user"]) && $_SESSION["user"]["role"] >= SHOW_MOD_PANEL_LEVEL) {?>
    <a class="nav-button" onclick="redirect_moderation()">Moderation</a>
    <?php } ?>
</div>      
        <div class="user-menu">
            <?= isset($_SESSION["user"]["email"])
                ? "<a class='nav-button' onclick='openIFrame(\"account\")'>" . $_SESSION["user"]["username"] . "</a>"
                : "<a class='nav-button' onclick='openIFrame(\"login\")'>Log in</a>"?>
            <?php if (isset($_SESSION["user"]["email"])) {?>
                <img class="logout-button img-button" src="/assets/img/logout-button.png" alt="Logout button" onclick="redirect_logout()">
                <!--<img class="logout-button" src="img/logout-button-filled.png" alt="Logout button">
                <div class="user-dropdown">
                    <a class='nav-button' onclick='openIFrame("account")'>Account</a>
                    <a class='nav-button' href='./logout.php'>Log out</a>
                </div>-->
            <?php }?>
        
        </div>
<?php }?>