
<div class="content explore-content">
    <?php require_once __DIR__ . '/sidebar.phtml'; ?>
    <div class="song-list">
        <div class="song-card preview">
            <span class="song-artist song-part">Artist</span>
            <span class="song-name song-part">Title</span>
            <span class="song-genre song-part">Genre</span>
            <span class="song-style song-part">Style</span>
        </div>
        <?php foreach($songs as $song){ ?>
        <div class="song-card">
            <a class="song-artist song-part" href="/artists/<?=$song["artistSlug"]?>"><?=$song["artistName"]?></a>
            <a class="song-name song-part"  href="/songs/<?=$song["songSlug"]?>"><?=$song["title"]?></a>
            <a class="song-genre song-part" href="/search?genre=<?=$song["genreID"]?>"><?=$song["genreName"]?></a>
            <a class="song-style song-part" href="/search?style=<?=$song["styleID"]?>"><?=$song["styleName"]?></a>
        </div>
        <?php } ?>
    </div>
</div>