        <div class="overlay-container" id="overlay-container" onclick="closeOverlayForm()">
            <form class="overlay-form account username" id="account-username" method="POST" onclick="event.stopPropagation()">
                <div class="overlay-desc">
                    <img class="close-form-img img-button" src="/assets/img/close-button.png" alt="Close button" onclick="closeOverlayForm()">
                    <span class="overlay-desc-text main">Change your username</span>
                    <span class="overlay-desc-text side">Enter a new username and your password.</span>
                </div>
                <label for="username">Username</label>
                <input class="overlay-input" type="text" id="username" name="username" required>
                <label for="password">Password</label>
                <input class="overlay-input" type="password" id="password-username" name="password-username" required>
                <div class="overlay-buttons">
                    <button type="button" class="overlay-button side" onclick="closeOverlayForm()">Cancel</button>
                    <input class="overlay-button main" type="submit" name="submit" value="Change Username">
                </div>
            </form>
            <form class="overlay-form account email" id="account-email" method="POST" onclick="event.stopPropagation()">
                <div class="overlay-desc">
                    <img class="close-form-img img-button" src="/assets/img/close-button.png" alt="Close button" onclick="closeOverlayForm()">
                    <span class="overlay-desc-text main">Update your email</span>
                    <span class="overlay-desc-text side">Enter a new email and your password.</span>
                </div>
                <label for="email">Email</label>
                <input class="overlay-input" type="text" id="email" name="email" required>
                <label for="password">Password</label>
                <input class="overlay-input" type="password" id="password-email" name="password-email" required>
                <div class="overlay-buttons">
                    <button type="button" class="overlay-button side" onclick="closeOverlayForm()">Cancel</button>
                    <input class="overlay-button main" type="submit" name="submit" value="Change Email">
                </div>
            </form>
            <form class="overlay-form account password" id="account-password" method="POST" onclick="event.stopPropagation()">
                <div class="overlay-desc">
                    <img class="close-form-img img-button" src="/assets/img/close-button.png" alt="Close button"  onclick="closeOverlayForm()">
                    <span class="overlay-desc-text main">Update your password</span>
                    <span class="overlay-desc-text side">Enter your current and new password.</span>
                </div>
                <label for="password">Current Password</label>
                <input class="overlay-input" type="text" id="password" name="password" required>
                <label for="password-new">New Password</label>
                <input class="overlay-input" type="password" id="password-new" name="password-new" required>
                <label for="password-new-conf">Confirm New Password</label>
                <input class="overlay-input" type="password" id="password-new-conf" name="password-new-conf" required>
                <div class="overlay-buttons">
                    <button type="button" class="overlay-button side" onclick="closeOverlayForm()">Cancel</button>
                    <input class="overlay-button main" type="submit" name="submit" value="Change Password">
                </div>
            </form>
            <form class="overlay-form account delete" id="account-delete" method="POST" onclick="event.stopPropagation()">
                <div class="overlay-desc">
                    <img class="close-form-img img-button" src="/assets/img/close-button.png" alt="Close button"  onclick="closeOverlayForm()">
                    <span class="overlay-desc-text main">Account deletion</span>
                    <span class="overlay-desc-text side">Are you sure you wish to delete your account?</span>
                </div>
                <label for="password">Current Password</label>
                <input class="overlay-input" type="text" id="password-delete" name="password-delete" required>
                <label for="password-delete-conf">Confirm  Password</label>
                <input class="overlay-input" type="password" id="password-delete-conf" name="password-delete-conf" required>
                <div class="overlay-buttons">
                    <button type="button" class="overlay-button side" onclick="closeOverlayForm()">Cancel</button>
                    <input class="overlay-button main delete" type="submit" name="submit" value="Delete Account">
                </div>
            </form>
        </div>
        <div class="content account-content">
            <h1 class="change-data-header-username"><?= $_SESSION["user"]["username"] ?></h1>
            <div class ="account-wrapper">
                <div class="personal-wrapper">
                        <h2 class="change-data-header">Username</h2>
                        <div class="change-data-wrapper">
                            <span class="change-data-info"><?= $_SESSION["user"]["username"] ?></span>
                            <button class="change-data-button" onclick="openOverlayForm('account', 'username')">Edit</button>
                        </div>
                        <h2 class="change-data-header">Email</h2>
                        <div class="change-data-wrapper">
                            <span class="change-data-info"><?= $_SESSION["user"]["email"] ?></span>
                            <button class="change-data-button" onclick="openOverlayForm('account', 'email')">Edit</button>
                        </div>
                        <h2 class="change-data-header">Password</h2>
                        <div class="change-data-wrapper">
                            <div></div>
                            <button class="change-data-button" onclick="openOverlayForm('account', 'password')">Change password</button>
                        </div>
                        <h2 class="change-data-header">Account deletion</h2>
                        <div class="change-data-wrapper">
                            <div></div>
                            <button class="change-data-button warning" onclick="openOverlayForm('account', 'delete')">Delete Account</button>
                        </div>
                </div>
            </div>
        </div>