<div class="content song-content">
    <?php if(isset($_SESSION["user"]["role"]) && $_SESSION["user"]["role"] >= EDIT_CONTENT_FULL) require_once __DIR__ . "/layouts/creation_overlay.phtml"?>
    <div class="song-header" style="background-color: <?=$song["colorHex"]?>;">
        <img class="song-cover" src="<?=buildImagePath($song["artistID"], $song["songSlug"])?>" alt="Cover image of <?=$song["title"]?>">
        <div class="song-info">
            <div class="song-title-wrapper">
                <h1 class="song-title"><?=$song["title"]?></h1>
                <h2 class="song-author">by <a class=song-author link" href="/artists/<?=$song["artistSlug"]?>"><?=$song["artistName"]?></a></h2>
                <?php /*if(isset($song["hasFeat"]) && $song["hasFeat"] == 1) { ?>
                    <h3>feat</h3>
                <?php }*/?>
                <?php if(isset($_SESSION["user"]["role"]) && $_SESSION["user"]["role"] >= EDIT_CONTENT_FULL) { ?>
                    <p class="song-edit-link" onclick="openOverlayForm('edit', 'form')">Edit</p>
                    <?php if(!$song["isPublic"]) { ?>
                        <form class="song-edit-form" method="POST">
                            <input type="hidden" name="songID" value="<?=$song["songID"]?>">
                            <input type="hidden" name="action" value="publish">
                            <input class="song-publish-button" type="submit" value="Publish">
                        </form>
                    <?php } else {?>
                        <form class="song-edit-form" method="POST">
                            <input type="hidden" name="songID" value="<?=$song["songID"]?>">
                            <input type="hidden" name="action" value="hide">
                            <input class="song-publish-button" type="submit" value="Hide">
                        </form>
                    <?php }?>
                    <form class="song-edit-form" method="POST">
                            <input type="hidden" name="songID" value="<?=$song["songID"]?>">
                            <input type="hidden" name="action" value="delete">
                            <input class="song-publish-button" type="submit" value="Delete">
                        </form>
                <?php } ?>
            </div>
            <h3 class="song-added-by">Added by <a href="/users/<?=$song["createdByUserID"]?>"><?=$song["createdByUsername"]?></a></h3>
        </div>
    </div>
    <p class="song-lyrics"><?=convertNewLinesToBr($song["lyrics"])?></p>
</div>