<div class="report-list">
    <?php if(!is_bool($users)){ foreach ($users as $user) { ?>
        <div class="report-card">
            <div class="report-header">
                <span class="report-id">#<?= $user["userID"] ?></span>
                <span class="report-type"><a href="/users/<?=$user["userID"]?>"> <?= $user["username"] ?></a></span>
            </div>
            <!--<div class="report-body">
                
            </div>-->
            <div class="report-footer">
                <p class="report-reason">Role: <?= roleNumToText($user["role"]) ?></p>
                <!--<span class="report-status"><?= ucfirst($submission["styleID"]) ?></span>
                <span class="report-date"><?= date("Y-m-d H:i", strtotime($submission["creationTimestamp"])) ?> by <?= $submission["createdByUsername"] ?></span>-->
                <form method="POST">
                    <input type="hidden" name="userID" value="<?= $user["userID"] ?>">
                    <input type="hidden" name="action" value="ban">
                    <input type="submit" class="resolve-btn" value="Ban" onclick="return confirm('Are you sure you want to ban this user?')">
                </form>
                <form method="POST">
                    <input type="hidden" name="userID" value="<?= $user["userID"] ?>">
                    <input type="hidden" name="action" value="demote">
                    <input type="submit" class="resolve-btn" value="Demote" onclick="return confirm('Are you sure you want to demote this user?')">
                </form>
                <form method="POST">
                    <input type="hidden" name="userID" value="<?= $user["userID"] ?>">
                    <input type="hidden" name="action" value="promote">
                    <input type="submit" class="resolve-btn" value="Promote" onclick="return confirm('Are you sure you want to promote this user?')">
                </form>
                <!--<button class="cancel-btn" onclick="redirect_submission('<?=$submission["songSlug"]?>')">Resolve</button>
                <button class="resolve-btn" onclick="redirect_submission('<?=$submission["songSlug"]?>')">Resolve</button>-->
            </div>
        </div>
    <?php }} else {?>
        <p>No users found! (what?)</p>
    <?php } ?>
</div>
