<?php
define("WEB_NAME","Akordemon");
define("WEB_URL","https://akordemon.gigaportal.pl");
define("ASSET_PATH","/assets/");
define("BASE_URL","/");
define("SHOW_MOD_PANEL_LEVEL",2);
define("SYSTEM_ROLE",5);
define("OWNER_ROLE",4);
define("ADMIN_ROLE",3);
define("MODERATOR_ROLE",2);
define("USER_ROLE",1);